<Project>
  <PropertyGroup>
    <Author>Ryan Martin</Author>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <VersionPrefix>0.0.1-alpha.1.0</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/universehq/hosting</RepositoryUrl>
  </PropertyGroup>
</Project>
